name: Manual rebuild
on:
  [workflow_dispatch]

permissions:
      contents: read
      packages: write

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      IMG_DATE: ${{ steps.date.outputs.IMG_DATE }}
    steps:
      - name: Get current date in RFC 3339
        id: date
        run: |
          IMG_DATE=$(date --rfc-3339=seconds | sed 's/ /T/')
          echo "IMG_DATE=${IMG_DATE}" >> $GITHUB_OUTPUT
          echo "The date is $IMG_DATE"

  get-version:
    runs-on: ubuntu-latest
    outputs:
      PKG_VER: ${{ steps.version.outputs.PKG_VER }}
    steps:
      - name: Add package source to APT
        run: |
          sudo apt install curl -y
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg https://brave-browser-apt-nightly.s3.brave.com/brave-browser-nightly-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg] https://brave-browser-apt-nightly.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-nightly.list
          sudo apt update

      - name: Get package version
        id: version
        run: |
          PKG_VER=$(apt list brave-browser-nightly | awk -F'[ /]' '/brave-browser-nightly/ {print $3}')
          echo "PKG_VER=${PKG_VER}" >> $GITHUB_OUTPUT
          echo "The package version is $PKG_VER"

  rebuild:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tibor309
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          build-args: |
            IMAGE_BUILD_DATE=${{ needs.get-date.outputs.IMG_DATE }}
          tags: |
            ghcr.io/tibor309/brave:nightly
            ghcr.io/tibor309/brave:${{ needs.get-version.outputs.PKG_VER }}
