name: Scheduled rebuild - stable
on:
  schedule:
    - cron: "10 0 1 * *"

jobs:
  get-version-stable:
    runs-on: ubuntu-latest
    outputs:
      PKG_VER: ${{ steps.getver.outputs.PKG_VER }}
    steps:
      - name: Add package source to APT
        run: |
          sudo apt install curl -y
          sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
          sudo apt update

      - name: Get package version
        id: getver
        run: |
          PKG_VER=$(apt list brave-browser | awk -F'[ /]' '/brave-browser/ {print $3}')
          echo "PKG_VER=${PKG_VER}" >> $GITHUB_OUTPUT
          echo "The package version is $PKG_VER"

  rebuild-stable:
    runs-on: ubuntu-latest
    needs: get-version-stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'stable'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tibor309
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push image for amd64/arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/tibor309/brave:latest
            ghcr.io/tibor309/brave:stable
            ghcr.io/tibor309/brave:${{ needs.get-version-stable.outputs.PKG_VER }}